# Generated by Django 3.1.1 on 2020-09-13 01:06

import audios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='cover',
            field=models.FileField(null=True, upload_to=audios.models.audio_cover_upload_path),
        ),
    ]
